### PR TITLE
adding resource folder including the logo

### PR DESCRIPTION
**Pull request by imrajat24**
resources including the hero-image and the social media svg's are added in the folder

### CODE REVIEW

**Comment by abhishek71994** [comment]
Please provide a description mentioning the issue it solves and how it solves it.

**Comment by abhishek71994** [comment]
Looks good to me. @palashg7563 just check in on the issue where I have mentioned you. @imrajat24 please update the description, it's not necessary but good git practise.

**Comment by imrajat24** [comment]
> Looks good to me. @palashg7563 just check in on the issue where I have mentioned you. @imrajat24 please update the description, it's not necessary but good git practise.

Done @abhishek71994

**Comment by palashg7563** [comment]
@imrajat24 for the hero image and the logo SVG is not available?

**Comment by imrajat24** [comment]
@palashg7563  Yes they are.

**Comment by palashg7563** [comment]
> @palashg7563 Yes they are.
But there is .jpg!!!

**Comment by imrajat24** [comment]
> > @palashg7563 Yes they are.
> > But there is .jpg!!!

Yes I know, I will be updating my PR shortly .

**Comment by imrajat24** [comment]
@palashg7563  done, you can check it now.

**Comment by DivyeshPuri** [comment]
@imrajat24 Looks Good 👍

**Comment by palashg7563** [comment]
@abhishek71994 looks fine

**Pull request merged**
